#!/usr/bin/env ruby

require 'github/markdown'

contents = []
title = false
last_line = ""

File.readlines(ARGV[0]).each do |line|
	if not title 
		if line =~ /^=+$/
			title = last_line
		else
			last_line = line
		end
	end
	line.gsub!(/\[([^\]]+)\]\(([^)]+)\)/) do |match|
		match.gsub!(/\.md/, ".html")
		match
	end
	contents << line
end

contents = contents.join("")

puts <<EOC
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>#{title}</title>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootswatch/3.3.2/cosmo/bootstrap.min.css">
<style>
body {
	padding-top: 20px;
	padding-bottom: 20px;
}
@media (min-width: 768px) {
	.container {
		max-width: 730px;
	}
}
</style>
</head>
<body>
<div class="container">
#{GitHub::Markdown.render(contents)}
<p class="text-muted text-center" style="margin-top: 40px;">
This website was rendered automatically from <em>libmbb</em>'s Markdown documentation.
</p>
</div>
</body>
</html>
EOC

