#!/usr/bin/env ruby
#
# Copyright (C) 2015 Jan Weil
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

if ARGV.length != 1
	$stderr.puts "usage: #{File.basename($0)} test_suite.c"
	exit 1
end

file = ARGV[0]

test_suite = File.basename(file).gsub('.c', '')
testh_included = false
tests = []
content = ""
File.readlines(file).each do |line|
	if line =~ /^#include "mbb\/test\.h"/
		testh_included = true
	end
	if line =~ /char \*(test_[^(]+)\(/
		tests.push($1)
	end
	content += line
end
if not testh_included
	$stderr.puts "#{file} does not include \"mbb/test.h\", skipping..."
	exit -1
end

puts <<EOC
#{content}

void textcolor(int attr, int fg, int bg)
{	char command[13];

	/* Command is the control command to the terminal */
	sprintf(command, "%c[%d;%d;%dm", 0x1B, attr, fg + 30, bg + 40);
	fprintf(stderr, "%s", command);
}

char *munt_all_tests()
{
	#{tests.map{|t| "MUNT_RUN_TEST(#{t});"}.join("\n")}
	
	return 0;
}

int main(void)
{
	char *result; 

	munt_tests_run = 0;

	fprintf(stderr, "\\nTest suite '#{test_suite}':\\n\\n");

	result = munt_all_tests();

	if (result != 0) {
		MUNT_COLOR(fprintf(stderr, "Test suite '#{test_suite}' FAILED (%d tests run)\\n", munt_tests_run));
	} else {
		fprintf(stderr, "Test suite '#{test_suite}' passed (%d %s run)\\n", munt_tests_run, munt_tests_run > 1 ? "tests" : "test");
	}

	exit(result == 0 ? EXIT_SUCCESS : EXIT_FAILURE);
}
EOC
